#!/usr/bin/env escript
%% Run with ERL_FLAGS='+S 1' in the compiled-example directory.
main(_) ->
    true = code:add_patha("."),
    {ok,<<"pong">>} = socket_examples:tcp(inet),
    {ok,<<"pong">>} = socket_examples:tcp(socket),
    <<"hello">> = socket_examples:udp(),
    {ok,P} = custom_io_server:start_link(),
    ok = io:put_chars(P, [16#3bb,$a,$\n,$b]),
    <<206,187>> = io:get_chars(P,"",1),
    <<"a\n">> = io:get_line(P,""),
    <<"b">> = io:get_chars(P,"",10),
    eof = io:get_line(P,""),
    <<>> = io:get_chars(P,"",0),
    eof = io:get_chars(P,"",1),
    {error,request} = io:request(P,{get_chars,unsupported,"",1}),
    {error,request} = io:request(P, unsupported),
    {ok,<<206,187,"a\nb">>} = custom_io_server:stop(P),
    {error,noproc} = custom_io_server:stop(P),
    {ok,Q} = custom_io_server:start_link(),
    ok = file:write(Q, <<"one\ntwo\nlast">>),
    {ok,<<"one\n">>} = file:read_line(Q),
    {ok,<<"two\n">>} = file:read_line(Q),
    {ok,<<"last">>} = file:read(Q,99),
    eof = file:read(Q,1),
    {ok,_} = custom_io_server:stop(Q),
    {ok,R} = custom_io_server:start_link(),
    ok = io:request(R,{put_chars,latin1,<<233>>}),
    <<233>> = io:request(R,{get_chars,latin1,"",1}),
    ok = io:put_chars(R,[16#3bb]),
    {error,no_translation} = io:request(R,{get_chars,latin1,"",1}),
    <<206,187>> = io:get_chars(R,"",1),
    {error,put_chars} = io:request(R,{put_chars,unicode,<<255>>}),
    {ok,_} = custom_io_server:stop(R),
    busy_check(),
    io:format("Socket, IO cursor/encoding/EOF and nonblocking driver checks passed.~n").
busy_check() ->
    ok = erl_ddll:load_driver(".","busy_port_drv"),
    P = open_port({spawn_driver,"busy_port_drv"},[binary]),
    Q = open_port({spawn_driver,"busy_port_drv"},[binary]),
    true = port_command(P,<<2,10,1>>),
    false = port_command(P,<<1,4,20>>,[nosuspend]),
    true = port_command(Q,<<1,6,20>>),
    receive {Q,{data,<<7,20>>}} -> ok after 100 -> error(port_isolation) end,
    %% This timer must run while the first driver's one-second timer is pending.
    Start = erlang:monotonic_time(millisecond),
    receive after 20 -> ok end,
    Elapsed = erlang:monotonic_time(millisecond)-Start,
    true = Elapsed < 500,
    receive {P,{data,<<20,1>>}} -> ok after 1500 -> error(delayed_reply) end,
    true = port_command(P,<<1,4,20>>,[nosuspend]),
    receive {P,{data,<<5,20>>}} -> ok after 100 -> error(retry) end,
    true = port_close(P), true = port_close(Q),
    process_flag(trap_exit,true),
    Bad = open_port({spawn_driver,"busy_port_drv"},[binary]),
    true = port_command(Bad,<<2,255,1>>),
    receive {'EXIT',Bad,badarg} -> ok after 100 -> error(validation) end.
