---

name: Build PDF
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install tools
        run: apk add git rsync erlang
      - name: Sort out git ownership
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: build
        run: make
      - name: release

        if: ${{ github.ref == 'refs/heads/master' }}
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: latest
          files: |
            beam-book.pdf

...
